[package]
name = "gpx_list"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1", features = [] }
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"